language: node_js
node_js: stable
os: osx

branches:
    only:
        - raw

before_install:
    - export TZ=Australia/Sydney

install:
    - npm install

before_script:
    - git config user.name "Kris Cotter"
    - git config user.email "mrcotter2013@gmail.com"
    - sed -i '' "s/__Travis_Token__/${Travis_Token}/" _config.yml

script:
    - npm run build
